### ISSUE TITLE
File missing in closed/NVIDIA

### ISSUE THREAD

**Issue by alice890308** [mlcommons/inference_results_v3.1#7]
Hi! I’m trying to run MLPerf on my A100 GPU with MIG mode. I use the implementation of Nvidia and follow [the document](https://github.com/mlcommons/inference_results_v3.1/tree/main/closed/NVIDIA). However, I encounter some questions…

1. I hope to run these benchmarks on MIG slices as described on [this page](https://github.com/mlcommons/inference_results_v3.1/blob/main/closed/NVIDIA/documentation/heterogeneous_mig.md#commands-to-run-the-heteromig-harness), but I didn’t find scripts/launch_heterogeneous_mig.py in the repo.

2. This implementation uses benchmark configuration for each benchmark, for example, [the server mode of resnet50](https://github.com/mlcommons/inference_results_v3.1/blob/main/closed/NVIDIA/configs/resnet50/Server/__init__.py). I wonder if you have a document to introduce each field with more detail? It can help me understand the meaning of every field and adjust them for my experiment.

**Comment by nv-ananjappa** [comment]
@alice890308 The 3.1 code of NVIDIA does not officially support running on A100 MIG. You can try some of our older submissions' code that supports MIG.
